version: '3.9'

services:
  patrimonio_system:
    build: .  # Altere para o diretório atual para construir a imagem
    container_name: patrimonio_system_container
    ports:
      - "5997:5997"
    volumes:
      - patrimonio-system:/app/db
    environment:
      - FLASK_ENV=production
      - TZ=America/Sao_Paulo
    stdin_open: true
    tty: true
    restart: always

volumes:
  patrimonio-system:
