version: '3.9'

services:
  patrimonio_system:
    build: .  # Altere para o diretório atual para construir a imagem
    container_name: patrimonio_system_container
    ports:
      - "5997:5997"
    volumes:
      - patrimonio-system:/app/db
    environment:
      - FLASK_ENV=production
      - TZ=America/Sao_Paulo
    stdin_open: true
    tty: true
    networks:
      - flask_network
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M   # Reservando uma quantidade mínima de memória
          cpus: '0.5'     # Reservando meio núcleo de CPU

volumes:
  patrimonio-system:
networks:
  flask_network:
    driver: bridge
